# Copyright © 2025–2026 Stefano Noferi & Admina contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""scripts/check-versions.py: version alignment across the manifests."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "scripts" / "check-versions.py"


def _load_script():
    spec = importlib.util.spec_from_file_location("check_versions", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


check_versions = _load_script()


def _write_repo(
    root: Path,
    version: str,
    *,
    cargo: str | None = None,
    runtime: str | None = None,
    locked_core: str | None = None,
    alias: str | None = None,
    alias_pin: str | None = None,
) -> Path:
    """Write the tracked manifests of a repository at ``version``.

    ``cargo`` is the crate version (Cargo.toml and Cargo.lock), ``runtime``
    the ``__version__`` and ``locked_core`` the admina-core entry of uv.lock;
    each defaults to ``version``. ``alias`` and ``alias_pin`` are the
    version of the ``admina`` alias and its admina-framework pin.
    """
    alias = alias or version
    alias_pin = alias_pin or version
    (root / "packaging" / "admina").mkdir(parents=True)
    (root / "packaging" / "admina" / "pyproject.toml").write_text(
        f'[project]\nname = "admina"\nversion = "{alias}"\n'
        f'dependencies = ["admina-framework=={alias_pin}"]\n',
        encoding="utf-8",
    )
    cargo = cargo or version
    runtime = runtime or version
    locked_core = locked_core or version
    (root / "admina").mkdir()
    (root / "core-rust").mkdir()
    (root / "pyproject.toml").write_text(
        f'[project]\nname = "admina-framework"\nversion = "{version}"\n', encoding="utf-8"
    )
    (root / "admina" / "__init__.py").write_text(f'__version__ = "{runtime}"\n', encoding="utf-8")
    (root / "uv.lock").write_text(
        "version = 1\nrevision = 3\n\n"
        f'[[package]]\nname = "admina-core"\nversion = "{locked_core}"\n'
        'source = { directory = "core-rust" }\n\n'
        f'[[package]]\nname = "admina-framework"\nversion = "{version}"\n'
        'source = { editable = "." }\n',
        encoding="utf-8",
    )
    (root / "core-rust" / "pyproject.toml").write_text(
        f'[project]\nname = "admina-core"\nversion = "{version}"\n', encoding="utf-8"
    )
    (root / "core-rust" / "Cargo.toml").write_text(
        f'[package]\nname = "admina_core"\nversion = "{cargo}"\nedition = "2021"\n',
        encoding="utf-8",
    )
    (root / "core-rust" / "Cargo.lock").write_text(
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n"
        f'[[package]]\nname = "admina_core"\nversion = "{cargo}"\n'
        'dependencies = [\n "serde",\n]\n',
        encoding="utf-8",
    )
    (root / "core-rust" / "uv.lock").write_text(
        "version = 1\nrevision = 3\n\n"
        f'[[package]]\nname = "admina-core"\nversion = "{version}"\n'
        'source = { editable = "." }\n',
        encoding="utf-8",
    )
    return root


@pytest.mark.parametrize(
    ("version", "expected"),
    [
        ("0.13.0-rc.1", "0.13.0rc1"),
        ("0.13.0-rc1", "0.13.0rc1"),
        ("0.13.0-alpha.2", "0.13.0a2"),
        ("0.13.0-beta.3", "0.13.0b3"),
        ("0.13.0rc1", "0.13.0rc1"),
        ("0.13.0", "0.13.0"),
        ("0.12.1", "0.12.1"),
    ],
)
def test_normalise_maps_cargo_prereleases_to_pep440(version, expected):
    assert check_versions.normalise(version) == expected


def test_aligned_release_candidate_passes(tmp_path, capsys):
    root = _write_repo(tmp_path, "0.13.0rc1", cargo="0.13.0-rc.1")

    assert check_versions.main(root) == 0
    out = capsys.readouterr().out
    assert "All versions aligned." in out
    assert "0.13.0-rc.1" in out  # the table shows each file's own spelling


def test_aligned_final_release_passes(tmp_path):
    root = _write_repo(tmp_path, "0.13.0")

    assert check_versions.main(root) == 0


@pytest.mark.parametrize(
    ("overrides", "drifting"),
    [
        ({"cargo": "0.13.0-rc.2"}, "core-rust/Cargo.toml"),
        ({"cargo": "0.13.0"}, "core-rust/Cargo.toml"),
        ({"runtime": "0.12.1"}, "admina/__init__.py"),
        ({"locked_core": "0.9.3"}, "uv.lock (admina-core)"),
        ({"alias": "0.12.2"}, "packaging/admina/pyproject.toml"),
        ({"alias_pin": "0.12.2"}, "packaging/admina (admina-framework pin)"),
    ],
)
def test_real_drift_fails(tmp_path, capsys, overrides, drifting):
    root = _write_repo(tmp_path, "0.13.0rc1", **{"cargo": "0.13.0-rc.1", **overrides})

    assert check_versions.main(root) == 1
    err = capsys.readouterr().err
    assert "drift from canonical 0.13.0rc1" in err
    assert drifting in err


def test_final_crate_does_not_match_a_release_candidate(tmp_path, capsys):
    root = _write_repo(tmp_path, "0.13.0", cargo="0.13.0-rc.1")

    assert check_versions.main(root) == 1
    assert "core-rust/Cargo.lock" in capsys.readouterr().err


def test_repository_versions_are_aligned():
    result = subprocess.run(
        [sys.executable, str(SCRIPT)], cwd=REPO, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stdout + result.stderr
