#!/bin/sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Admina — Secret Bootstrap
#
# Generates .env with random credentials if it does not exist
# or if it contains only comments/empty values.
#
# Usage:
#   ./scripts/bootstrap-secrets.sh        # generate if needed
#   ./scripts/bootstrap-secrets.sh --force # always regenerate
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -e

ENV_FILE="${ENV_FILE:-.env}"
FORCE="${1:-}"

# Generate a random hex string (portable: works on macOS + Linux)
rand_hex() {
    od -An -tx1 -N"$1" /dev/urandom | tr -d ' \n'
}

# Generate a random alphanumeric+symbol password
rand_password() {
    LC_ALL=C tr -dc 'A-Za-z0-9!@#%&*+-' < /dev/urandom | head -c "${1:-20}" || true
}

# Check if .env already has real secrets (not just placeholders)
has_secrets() {
    [ -f "$ENV_FILE" ] && grep -qE '^ADMINA_API_KEY=.{10,}' "$ENV_FILE" 2>/dev/null
}

if has_secrets && [ "$FORCE" != "--force" ]; then
    echo "  Secrets already configured in $ENV_FILE"
    echo "  Use --force to regenerate."
    exit 0
fi

API_KEY=$(rand_hex 32)
PASSWORD=$(rand_password 20)
WEBUI_KEY=$(rand_hex 32)

cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by admina bootstrap. Do not edit manually.
# Regenerate with: admina password reset  (or ./scripts/bootstrap-secrets.sh --force)

ADMINA_API_KEY="${API_KEY}"
ADMINA_DASHBOARD_PASSWORD="${PASSWORD}"
CLICKHOUSE_PASSWORD="${PASSWORD}"
GRAFANA_ADMIN_PASSWORD="${PASSWORD}"
MINIO_SECRET_KEY="${PASSWORD}"
WEBUI_SECRET_KEY="${WEBUI_KEY}"
ENVEOF

chmod 600 "$ENV_FILE"

echo ""
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Admina credentials generated!"
echo ""
echo "    API Key:    ${API_KEY}"
echo "    Password:   ${PASSWORD}"
echo "                (dashboard, Grafana, MinIO, ClickHouse)"
echo ""
echo "    Dashboard login:  admin / ${PASSWORD}"
echo "    Grafana login:    admin / ${PASSWORD}"
echo ""
echo "    Save these now — run this script with --force to regenerate."
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
